version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user # in real life this would never be hardcoded, but here its fine since it's a toy project
      POSTGRES_PASSWORD: password # same for the pwd
      POSTGRES_DB: crypto_trading
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
