CREATE TYPE transaction_type AS ENUM ('buy', 'sell');
CREATE TABLE users(
	did	integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	username	varchar(40) NOT NULL,
	cash	double precision
);

CREATE TABLE transactions(
	did	integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id	integer	references users(did),
	date_produced	date,
	symbol	varchar(20) NOT NULL,
	price_per_share	double precision NOT NULL,
	shares	double precision NOT NULL,
	action	transaction_type NOT NULL
);

CREATE TABLE holdings(
	did	integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id integer references users(did),
	invested	double precision,
	symbol	varchar(20) NOT NULL,
	shares	double precision,
	avg_price	double precision
);
